### ISSUE TITLE
Error : Could not determine if the _bulk_get endpoint is supported

### ISSUE THREAD

**Issue by cmijum** [cloudant/sync-cordova-plugin#104]
Hi,
I am facing an issue with the replication.. when i call the 'create pull replication' i get the following exception:
**java.lang.RuntimeException: Could not determine if the _bulk_get endpoint is supported**

cloudant-sync plugin version i'm using is 0.4.1.
Please help me out, i'm stuck with this issue.

**Comment by ricellis** [comment]
The first communication with the server is to try and see if it is possible to use the `_bulk_get` optimization. If the response code isn't a `404` or a `405` then this exception is thrown.

Are you able to see the cause in that stack trace, there should be a `CouchException` that gives some more detail about what didn't work (e.g. if the credentials were incorrect or similar).

**Comment by cmijum** [comment]
Hi Ricellis, My service is returning a status of 405 with this response
{
    "error": "method_not_allowed",
    "reason": "Only POST allowed"
}
and when i do a  ../db/_all_docs it returns all the documents
Note: I'am Using a Free Trail version of the IBM Cloudant.
What is the solution to this.. How do i resolve this issue of _bulk_get

**Comment by ricellis** [comment]
A `405` is expected if you try to `HEAD` or `GET` the `_bulk_get` endpoint (which is what the code does to test if it is available). I don't see how you could get a `405` and the `RuntimeException` (the code is [here](https://github.com/cloudant/sync-android/blob/2.0.2/cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java#L701)).
Can you post the whole stack trace?

**Comment by cmijum** [comment]
This is the code i am using to do the replication:
`	var uri = 'https://*************@cloudant.com/mydb';   
        var pullReplicatorOptions = {
            source: uri,
            target: this.datastore
        };
        this._loggerService.info('Replicate from the remote to local database');        
            Replicator.create(pullReplicatorOptions).then(function (replicator) {
                replicator.on('complete', function (numDocs) {
                    this._loggerService.info('Replicated ' + numDocs + ' documents');
                    replicator.destroy();                    
                });

                replicator.on('error', function (message) {
                    this._loggerService.error('Error replicating to Local: ',message);
                    replicator.destroy();
                });
                replicator.start(); 
            }).done(); `

and this is my console output : 

> Error replicating to Local:  java.lang.RuntimeException: Could not determine if the _bulk_get endpoint is supported

**Comment by ricellis** [comment]
Looking at that code sample the `uri` does not look to be correct, it should be of the form:
`https://user:pass@account.cloudant.com/mydb` possibly that is just a typo?

I can also see from the service logs a number of `503` response codes for the `_bulk_get` checks coming from old `cloudant.com` accounts. The old style [cloudant.com accounts were retired on March 31](https://cloudant.com/shared-plan-retirement/). Did you migrate your account to IBM Cloud? Is your `uri` in your replication code correct for your new migrated account?

If you need help with account migration you should contact Cloudant support.

**Comment by cmijum** [comment]
Thank you so much.. @ricellis  It worked. it was actually the URI issue.. I changed the username and password but did't notice the uri change from the old version..
Thanks once again.. you can close this issue.
