### ISSUE TITLE
"Require is not defined" = configuration faault?

### ISSUE THREAD

**Issue by acutetech** [cloudant/sync-cordova-plugin#75]
I have followed instructions and built an Android app (using latest Cordova CLI). As soon as execution reaches this line: var DatastoreManager = require('cloudant-sync.DatastoreManager'); I receive an error "Uncaught reference: require is not defined.

When I hack require() to cordova.require() the problem moves on and I get "Uncaught TypeError: DatastoreManager.openDatastore is not a function".

This sounds like a simple configuration error or missing path error but I am not sure where to look. 

Can anyone help? Is there a complete, working example I can copy? (Is there somewhere better to post these questions?)

Thanks - Charles

**Comment by ricellis** [comment]
Thanks for reporting this I think our `README` could do with some clarification.

You are correct that `cordova.require(...)` is the necessary require call. After that you need to access the `DatastoreManager` and call `DatastoreManager()` to get the first promise for example:

```javascript
var DatastoreManager = cordova.require('cloudant-sync.DatastoreManager').DatastoreManager;
DatastoreManager()
    .then(function(datastoreManager) {
        return datastoreManager.openDatastore('my_datastore');
    })
    .done()
```

**Comment by acutetech** [comment]
OK, Rick, progress! I am now syncing with a remote database at cloudant.com. Still some issues to resolve at my end, again that can probably be overcome with your improved documentation. I may post further issues here.

Can I suggest that you thoroughly review all of the documentation for accuracy. For example in replication.md this code won't work:
var DatastoreManager = require('com.cloudant.sync.')
var ReplicatorBuilder = require('com.cloudant.sync.ReplicatorBuilder');

Looks like it should be:
    var DatastoreManager = cordova.require('cloudant-sync.DatastoreManager').DatastoreManager();
    var Replicator = cordova.require('cloudant-sync.Replicator');

In case it could be useful to add to your documentation, I build a Node-RED flow that does trivial Cloudant.com database operations: I have found it useful to have that while I work with my Android device:
https://flows.nodered.org/flow/411bab7d9872bac32ad1ebba06c14a37

**Comment by acutetech** [comment]
Also, it might be useful to run jsdoc (or similar) over your own source files and make the results directly accessible from Github.

**Comment by ricellis** [comment]
Thanks I did spot those `require` blocks in `replication.md` and a few other errors. We'll cover remaining issues in `replication.md` under #79.
