### ISSUE TITLE
embedFramework.sh hook uses a hard-coded iOS PRODUCT_NAME 

### ISSUE THREAD

**Issue by brynh** [cloudant/sync-cordova-plugin#76]
The `embedFramework.sh` script that is run after a `platform add` for iOS uses a hard-coded `PRODUCT_NAME`. This means that if the `name` argument passed to `cordova create` is anything other than `HelloCordova`, the iOS app will crash on startup because the `LD_RUNPATH_SEARCH_PATHS` don't point to the required locations.

**Comment by woyehenni** [comment]
@brynh 
Hi,
with your code, the iOS app do not crash on the simulator, but still crashed on the real iOS device.
do you have any idea?
thanks.

I tested on
iOS version: 10.2
iOS version: 8.3

**Comment by brynh** [comment]
@woyehenni Thank you for pointing this out. I've added some instructions for [how to configure for running on an iOS device](https://github.com/cloudant/sync-cordova-plugin#running-on-an-ios-device)

**Comment by woyehenni** [comment]
@brynh 
Thanks for replay. but it does not work for me.
there has some link errors.
please refer to the images.

![image](https://cloud.githubusercontent.com/assets/3880931/24234956/e4490bd0-0fd5-11e7-8f4f-7549b6e29a5f.png)
![image](https://cloud.githubusercontent.com/assets/3880931/24234963/ee54e0e0-0fd5-11e7-99f3-b7988be87a04.png)
![image](https://cloud.githubusercontent.com/assets/3880931/24235128/c18ec99e-0fd6-11e7-9ae5-86229abcd552.png)
![image](https://cloud.githubusercontent.com/assets/3880931/24235137/d75f5dc4-0fd6-11e7-9e38-7f435d9951fd.png)

**Comment by brynh** [comment]
@woyehenni From the screenshots you sent, it looks like your _Linked Frameworks and Libraries_ are wrong.  When you execute step 4 of the new [configuration process](https://github.com/cloudant/sync-cordova-plugin/blob/9abeaea318a6376d4b344fd2b33ce7a431335d92/README.md#running-on-an-ios-device) it should add `CocoaLumberjack.framework`, `CDTDatastore.framework` and `FMDB.framework` back to _Linked Frameworks and Libraries_ as well as putting them in _Embedded Binaries_ and you should leave them in there.  

Step 3 (deleting the frameworks from _Linked Frameworks and Libraries_) isn't strictly necessary, but if you don't do it the frameworks all end up in _Linked Frameworks and Libraries_ twice.

I also should have mentioned in my previous comment that these changes are not yet released, so to test this you would need to use the version of the plugin from our `master` branch using
> cordova plugin add https://github.com/cloudant/sync-cordova-plugin

without specifying a version as the changes to one of the hook scripts are also necessary.

If you can retry this process and make sure when you're done `CocoaLumberjack.framework`, `CDTDatastore.framework` and `FMDB.framework` are in both _Embedded Binaries_ **and** _Linked Frameworks and Libraries_ then if it works for you I can add some clarification to step 4 to make it clear they should then be in both sections.
