### ISSUE TITLE
How to get record count

### ISSUE THREAD

**Issue by hamzahio** [cloudant/sync-cordova-plugin#89]
Good day cloudant

I search for count function but there no doc on it can you point to me where I can found it.

Thanks.

**Comment by ricellis** [comment]
For the local or remote database?

**Comment by hamzahio** [comment]
Local

**Comment by ricellis** [comment]
You can select the documents you want to count with a query. The query language doesn't have a count, but it does have `$exists` so for example if you wanted every document you could probably use a selector something like:
```js
selector: { _id: {$exists: true}}
```
(or whatever field you wanted) to get a match for every doc and use the size of the result set to get a count.
Just make sure you have created a suitable index for the field.
