### ISSUE TITLE
Android: Encryption does not work

### ISSUE THREAD

**Issue by codagowtham** [cloudant/sync-cordova-plugin#98]
I am using sync-cordova-plugin to store data in the mobile device and I want to encrypt the database.

I tried to follow the instructions provided in the Encryption.md documentation. 

I couldn't find SQLCipher .jar and .so files in the provided link and the least version provided in maven central is 3.3.1 and latest is 3.5.9 where only .aar files are provided.

I managed to get SQLCipher 3.0.1 .jar and .so files and tried to run the application. 

When I open the datastore passing the options parameter, I get the following error

`nodeback is not a function`

![image](https://user-images.githubusercontent.com/33635978/37476286-c2c013f8-289a-11e8-9652-b96f65d46896.png)

Any help on this is appreciated! It would be great if we have a updated documentation for encryption.

Note: Without passing the options parameter, the datastore seems to work fine.

**Comment by ricellis** [comment]
Sorry, it appears that the encryption feature was removed from this library before release by #38 / #40. It looks like this removal was incomplete leaving some code remnants and documentation behind, which gave the impression that on-device datastore encryption was still available, but it isn't.

The documentation will be updated to match the capabilities of the library.
