### ISSUE TITLE
iOS: Encryption does not build project

### ISSUE THREAD

**Issue by codagowtham** [cloudant/sync-cordova-plugin#99]
I could not build the iOS project with encryption enabled and following the steps on the documentation.

With some help from Richard Ellis, I was able to progress through to different stage of errors.

However, below are the steps I have done so far,

1) Cloned [https://github.com/cloudant/CDTDatastore](https://github.com/cloudant/CDTDatastore) locally
2) Checked out tag 1.2.1
3) Set Environment Variable `ENCRYPT_DATABASE=1`
4) Run `pod install`
5) build iphoneos project using `xcodebuild -workspace CDTDatastore.xcworkspace -scheme CDTDatastore -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BUILD_DIR=/path/to/output clean build`
6) build iphonesimulator project using `xcodebuild -workspace CDTDatastore.xcworkspace -scheme CDTDatastore -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR=/path/to/output clean build`
7) Ran lipo trying to merge the files `lipo -create -output /path/to/merged /path/to/Release-iphoneos/CDTDatastore.framework/CDTDatastore /path/to/Release-iphonesimulator/CDTDatastore.framework/CDTDatastore`
8) Repeat 5 to 7 for FMDB and CocoaLumberjack frameworks
9) Copy the 3 merged binaries into my project (plugins/cloudant-sync/libs/ios folder) 
10) ran npm install inside the cloudant-sync folder to run past through dependency on q.js was not found in node_modules of cloudant-sync
11) Finally ran cordova build ios

Getting this error,
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CDTDatastore", referenced from:
      l_OBJC_$_CATEGORY_CDTDatastore_$_Manager in CDTSyncPlugin.o
  "_OBJC_CLASS_$_CDTDocumentRevision", referenced from:
      objc-class-ref in CDTSyncPlugin.o
  "_OBJC_CLASS_$_CDTPushReplication", referenced from:
      objc-class-ref in CDTSyncPlugin.o
  "_OBJC_CLASS_$_CDTPullReplication", referenced from:
      objc-class-ref in CDTSyncPlugin.o
  "_OBJC_CLASS_$_CDTUnsavedDataAttachment", referenced from:
      objc-class-ref in CDTSyncPlugin.o
  "_OBJC_CLASS_$_CDTReplicatorFactory", referenced from:
      objc-class-ref in CDTSyncPlugin.o
  "_OBJC_CLASS_$_CDTDatastoreManager", referenced from:
      objc-class-ref in CDTSyncPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1` 

Kindly help resolving this issue and would greatly appreciate if the documentation is updated accordingly!

**Comment by ricellis** [comment]
Sorry, it appears that the encryption feature was removed from this library before release by #38 / #40. It looks like this removal was incomplete leaving some code remnants and documentation behind, which gave the impression that on-device datastore encryption was still available, but it isn't.

The documentation will be updated to match the capabilities of the library.
